// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWNApvNw8p-JE0mbIchKfZol_-aGfZVJI',
    appId: '1:731660820861:web:09812a8dd64a0e06c16c14',
    messagingSenderId: '731660820861',
    projectId: 'ridepro-dbafe',
    authDomain: 'ridepro-dbafe.firebaseapp.com',
    storageBucket: 'ridepro-dbafe.firebasestorage.app',
    measurementId: 'G-0RQP7EZRCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjhsmpTqlyJRfjURGLs2JG1dyrGE3bnag',
    appId: '1:731660820861:android:42d34edf5d3e0abbc16c14',
    messagingSenderId: '731660820861',
    projectId: 'ridepro-dbafe',
    storageBucket: 'ridepro-dbafe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWNApvNw8p-JE0mbIchKfZol_-aGfZVJI',
    appId: '1:731660820861:web:10f330e27c347846c16c14',
    messagingSenderId: '731660820861',
    projectId: 'ridepro-dbafe',
    authDomain: 'ridepro-dbafe.firebaseapp.com',
    storageBucket: 'ridepro-dbafe.firebasestorage.app',
    measurementId: 'G-VNJ8RLNLQY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOlFzTpQgmdq4xObfZcPvr4y0JwhBK1z4',
    appId: '1:731660820861:ios:8d99c2d330181c16c16c14',
    messagingSenderId: '731660820861',
    projectId: 'ridepro-dbafe',
    storageBucket: 'ridepro-dbafe.firebasestorage.app',
    iosClientId: '731660820861-09qqql10tm55tbkk20v0ug6a7sj964ur.apps.googleusercontent.com',
    iosBundleId: 'com.korixa.app',
  );
}
